"""
run_agent.py — Tier-1 demo. Runs the full engine and prints the roadmap.

Two modes:
  python run_agent.py            -> offline fixture (your profile). No Kugiro needed.
  python run_agent.py --kugiro   -> live: pull profile+jobs from Kugiro over MCP.

The offline mode is your guaranteed demo: it exercises Claude codegen + the
Daytona sandbox end to end, independent of Alex's server being up.
"""
import asyncio
import sys

from dotenv import load_dotenv

load_dotenv()

from agent.core import generate_growth_roadmap, generate_from_kugiro  # noqa: E402

# A realistic fixture: senior backend dev pivoting to AI Product roles in Berlin.
FIXTURE_PROFILE = {
    "target_roles": ["AI Product Manager", "Senior Backend Engineer"],
    "keywords": ["python", "fastapi", "sql", "rest", "postgresql"],
    "seniority": ["senior"],
}

# Stand-in for Kugiro's scanned jobs (shape matches list_jobs/get_job output).
FIXTURE_JOBS = [
    {"role": "AI Product Manager", "industry": "AI", "notes": "python llm product management aws"},
    {"role": "Senior Backend Engineer", "industry": "SaaS", "notes": "python kubernetes docker aws postgresql"},
    {"role": "Platform Engineer", "industry": "Fintech", "notes": "kubernetes terraform aws ci/cd go"},
    {"role": "ML Engineer", "industry": "AI", "notes": "python machine learning llm docker"},
    {"role": "Backend Engineer", "industry": "E-commerce", "notes": "python sql aws kubernetes react"},
    {"role": "AI Solutions Architect", "industry": "AI", "notes": "aws llm system design kubernetes"},
]


def print_roadmap(result: dict) -> None:
    print("\n" + "=" * 60)
    print("  GROWTH ROADMAP")
    print("=" * 60)
    cand = result.get("candidate", {})
    print(f"  Candidate skills : {', '.join(cand.get('skills', []))}")
    print(f"  Target roles     : {', '.join(cand.get('target_roles', []))}")
    cov = result["gap_summary"]["covered"]
    print(f"\n  Already have (in-demand): {', '.join(cov) if cov else '-'}")
    print(f"\n  Recommended learning path (ranked by impact):\n")
    for i, r in enumerate(result["roadmap"], 1):
        cost = f"EUR {r['cost_eur']}" if r["cost_eur"] is not None else "n/a"
        weeks = f"{r['weeks']}w" if r["weeks"] is not None else "n/a"
        print(f"  {i}. {r['skill'].upper()}  (+{r['projected_score_uplift']} fit, "
              f"in {r['appears_in_pct_of_target_jobs']}% of target jobs)")
        print(f"     -> {r['course']} | {r['provider']} | {cost} | {weeks}\n")
    print("=" * 60)
    print("  Scoring code was generated by Claude and executed in an")
    print("  isolated Daytona sandbox. Auditable logic, not a black box.")
    print("=" * 60 + "\n")
    if "--show-code" in sys.argv and result.get("_generated_code"):
        print("--- The exact program Claude generated and ran in the sandbox ---\n")
        print(result["_generated_code"])
        print("\n" + "-" * 60 + "\n")


def main() -> None:
    if "--kugiro" in sys.argv:
        print("Pulling profile + jobs live from Kugiro over MCP...")
        result = asyncio.run(generate_from_kugiro())
    else:
        print("Running offline fixture (no Kugiro needed)...")
        result = generate_growth_roadmap(FIXTURE_PROFILE, FIXTURE_JOBS)
    print_roadmap(result)


if __name__ == "__main__":
    main()
